services:
  - type: web
    name: ielts-backend
    env: node
    plan: free
    buildCommand: npm install && npm rebuild bcrypt
    startCommand: npm start
    envVars:
      - key: PORT
        value: 4000
      - key: NODE_VERSION
        value: 18.x
